services:
  # Backend Service
  - type: web
    name: cognivasc-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    envVars:
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 8000
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: https://cognivasc-frontend.onrender.com
    disk:
      name: cognivasc-disk
      mountPath: /app/data
      sizeGB: 1

  # Frontend Service
  - type: web
    name: cognivasc-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://cognivasc-backend.onrender.com
